services:
  app:
    container_name: server
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDB:3306/hyeongarl?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: 'hyeongarl'
      SPRING_DATASOURCE_PASSWORD: 'hyeongarl@45'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hyeongarl_network

  mysql:
    container_name: mysqlDB
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: 'hyeongarl'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
      MYSQL_USER: 'hyeongarl'
      MYSQL_HOST: '%'
      MYSQL_PASSWORD: 'hyeongarl@45'
    ports:
      - "3307:3306"
    networks:
      - hyeongarl_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 2

networks:
  hyeongarl_network: